-- =============================================================
-- 07_revenue_by_plan.sql
-- Project: Subscriber Lifecycle Analytics
-- Description: Compares revenue, churn, and subscriber volume
--              across contract types to identify which plans
--              drive the most value and retention.
-- Author: Mena Melaku
-- =============================================================


SELECT

  contract_type,

  -- Volume of subscribers per plan
  COUNT(customer_id)                            AS total_subscribers,

  -- Churn rate per plan
  ROUND(COUNTIF(churn_label = TRUE) * 100.0
    / COUNT(customer_id), 2)                    AS churn_rate_pct,

  -- Average monthly charge per plan
  ROUND(AVG(monthly_charge), 2)                 AS avg_monthly_charge,

  -- Average total revenue per subscriber per plan
  ROUND(AVG(total_revenue), 2)                  AS avg_revenue_per_subscriber,

  -- Total revenue generated by each plan
  ROUND(SUM(total_revenue), 2)                  AS total_revenue,

  -- Revenue share: what percentage of total revenue does each plan contribute
  ROUND(SUM(total_revenue) * 100.0
    / SUM(SUM(total_revenue)) OVER (), 2)       AS revenue_share_pct,

  -- Average satisfaction per plan
  ROUND(AVG(satisfaction_score), 2)             AS avg_satisfaction,

  -- Average tenure per plan
  ROUND(AVG(tenure_months), 1)                  AS avg_tenure_months

FROM `subscriber-lifecycle-analytics.telco_churn.master_subscribers`
GROUP BY contract_type
ORDER BY total_revenue DESC;